version: "3.9"
services:
  humidity-sensor:
    image: lab3/humidity-sensor
    ports:
      - "8501:8501"
    environment:
      - EUREKA_HOST=http://eureka-server:8761/eureka/
  temperature-sensor:
    image: lab3/temperature-sensor
    ports:
      - "8502:8502"
    environment:
      - EUREKA_HOST=http://eureka-server:8761/eureka/
    healthcheck:
      test: "curl --fail --silent http://localhost:8501/actuator/health | grep UP || exit 0"
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 8s
  aggregator:
    image: lab3/aggregator
    ports:
      - "8080:8080"
    environment:
      - CONFIG_HOST=http://config-server:8888/
      - EUREKA_HOST=http://eureka-server:8761/eureka/
    depends_on:
      temperature-sensor:
        condition: service_healthy

